### ISSUE TITLE
BME280I2C.h Header Location

### ISSUE THREAD

**Issue by matteshe** [sqs-dach/IoT-on-Campus-2018#1]
File: nodeAtest.ino

Line: #include <BME280I2C.h>

Which library are you installed in ArduinoIDE to get this header?

**Comment by thomo** [comment]
I use the BME280 library by Tyler Glenn (https://github.com/finitespace/BME280) and FastLED v3.1.6 by Daniel Garcia (https://github.com/FastLED/FastLED).

Sketch -> Include Library -> Manage Libraries -> Search for "BME280" -> select "BME280 by Tyler Glenn"

I also will include a note in the sources.
